// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using InternProj.Db;

namespace InternProj.Db.Migrations
{
    [DbContext(typeof(EServicesDbContext))]
    [Migration("20201109100346_v2")]
    partial class v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UnFelDeFinal.Domain.BillingDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityHallId")
                        .HasColumnType("int");

                    b.Property<int?>("ElectronicServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("ElectronicServicePaymentInfoId")
                        .HasColumnType("int");

                    b.Property<int>("IbanId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("IsPayedDataTime")
                        .HasColumnType("SMALLDATETIME");

                    b.HasKey("Id");

                    b.HasIndex("CityHallId");

                    b.HasIndex("ElectronicServiceId");

                    b.HasIndex("ElectronicServicePaymentInfoId");

                    b.HasIndex("IbanId");

                    b.ToTable("BillingDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityHallId = 1,
                            ElectronicServiceId = 1,
                            ElectronicServicePaymentInfoId = 1,
                            IbanId = 1,
                            IsPayed = false
                        },
                        new
                        {
                            Id = 2,
                            CityHallId = 2,
                            ElectronicServiceId = 2,
                            ElectronicServicePaymentInfoId = 1,
                            IbanId = 2,
                            IsPayed = false
                        });
                });

            modelBuilder.Entity("UnFelDeFinal.Domain.CityHall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BanckAccount")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("CityHalls");

                    b.HasCheckConstraint("CK_CityHall_Name", "Name Like '%___%'");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BanckAccount = "BanckAccount1",
                            Name = "Ciorescu"
                        },
                        new
                        {
                            Id = 2,
                            BanckAccount = "BanckAccount2",
                            Name = "Bacioi"
                        },
                        new
                        {
                            Id = 3,
                            BanckAccount = "BanckAccount3",
                            Name = "Bubuieci"
                        },
                        new
                        {
                            Id = 4,
                            BanckAccount = "BanckAccount4",
                            Name = "Budesti"
                        });
                });

            modelBuilder.Entity("UnFelDeFinal.Domain.ElectronicService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("SMALLMONEY");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.Property<string>("TreasureAccount")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasAlternateKey("TreasureAccount");

                    b.ToTable("ElectronicService");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 20.52m,
                            Name = "test 1 service ",
                            TreasureAccount = "Treasure1"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 12.22m,
                            Name = "test 2 service ",
                            TreasureAccount = "Treasure2"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 22.12m,
                            Name = "test 3 service ",
                            TreasureAccount = "Treasure3"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 2.52m,
                            Name = "test 4 service ",
                            TreasureAccount = "Treasure4"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 44.42m,
                            Name = "test 5 service ",
                            TreasureAccount = "Treasure5"
                        });
                });

            modelBuilder.Entity("UnFelDeFinal.Domain.ElectronicServicePaymentInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("SMALLMONEY");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Idnx")
                        .IsRequired()
                        .HasColumnType("char(13)");

                    b.Property<string>("PayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("PayerType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ElectronicServicePaymentInfo");

                    b.HasCheckConstraint("CK_PayerInfo_Amount", "Amount Like '%[0-9]%'");

                    b.HasCheckConstraint("CK_PayerInfo_Idnx", "Idnx Like '[012]____________'");

                    b.HasCheckConstraint("CK_PayerInfo_PayerName", "PayerName Like '%_____%'");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 20.2m,
                            DataTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Idnx = "0123456789012",
                            PayerName = "payer name 1",
                            PayerType = 0
                        },
                        new
                        {
                            Id = 2,
                            Amount = 10.2m,
                            DataTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Idnx = "0123456789013",
                            PayerName = "payer name 2",
                            PayerType = 1
                        });
                });

            modelBuilder.Entity("UnFelDeFinal.Domain.Iban", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityHallId")
                        .HasColumnType("int");

                    b.Property<int?>("ElectronicServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("char(24)");

                    b.HasKey("Id");

                    b.HasIndex("CityHallId");

                    b.HasIndex("ElectronicServiceId");

                    b.ToTable("Ibans");

                    b.HasCheckConstraint("CQ_Iban_Name", "Name Like 'MD______________________'");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityHallId = 1,
                            ElectronicServiceId = 1,
                            Name = "MD_____________________1"
                        },
                        new
                        {
                            Id = 2,
                            CityHallId = 2,
                            ElectronicServiceId = 1,
                            Name = "MD_____________________2"
                        },
                        new
                        {
                            Id = 3,
                            CityHallId = 3,
                            ElectronicServiceId = 1,
                            Name = "MD_____________________3"
                        },
                        new
                        {
                            Id = 4,
                            CityHallId = 4,
                            ElectronicServiceId = 1,
                            Name = "MD_____________________4"
                        },
                        new
                        {
                            Id = 5,
                            CityHallId = 1,
                            ElectronicServiceId = 2,
                            Name = "MD_____________________5"
                        },
                        new
                        {
                            Id = 6,
                            CityHallId = 2,
                            ElectronicServiceId = 2,
                            Name = "MD_____________________6"
                        });
                });

            modelBuilder.Entity("UnFelDeFinal.Domain.BillingDetails", b =>
                {
                    b.HasOne("UnFelDeFinal.Domain.CityHall", "CityHall")
                        .WithMany("BillingDetails")
                        .HasForeignKey("CityHallId");

                    b.HasOne("UnFelDeFinal.Domain.ElectronicService", "ElectronicService")
                        .WithMany("BillingDetails")
                        .HasForeignKey("ElectronicServiceId");

                    b.HasOne("UnFelDeFinal.Domain.ElectronicServicePaymentInfo", "ElectronicServicePaymentInfo")
                        .WithMany("BillingDetails")
                        .HasForeignKey("ElectronicServicePaymentInfoId");

                    b.HasOne("UnFelDeFinal.Domain.Iban", "Iban")
                        .WithMany("BillingDetails")
                        .HasForeignKey("IbanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("UnFelDeFinal.Domain.Iban", b =>
                {
                    b.HasOne("UnFelDeFinal.Domain.CityHall", "CityHall")
                        .WithMany("Iban")
                        .HasForeignKey("CityHallId");

                    b.HasOne("UnFelDeFinal.Domain.ElectronicService", "ElectronicService")
                        .WithMany("Iban")
                        .HasForeignKey("ElectronicServiceId");
                });
#pragma warning restore 612, 618
        }
    }
}
